# Generated by Django 6.1.1 on 2026-09-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(default='', max_length=500),
        ),
    ]
